# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TxclUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.QtGui import QPixmap, QFont

import TxclUI
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QAction, qApp, QWidget, QPushButton, QMessageBox, QFileDialog
import sys
import predict



class Ui_TxclUIClass(object):
    def __init__(self):
        self.file_name1 = ''  # 定义一个实例变量

    def setupUi(self, TxclUIClass):
        TxclUIClass.setObjectName("TxclUIClass")
        TxclUIClass.resize(1017, 680)
        self.centralWidget = QtWidgets.QWidget(TxclUIClass)
        self.centralWidget.setObjectName("centralWidget")
        self.widget_4 = QtWidgets.QWidget(self.centralWidget)
        self.widget_4.setGeometry(QtCore.QRect(10, 10, 1001, 641))
        self.widget_4.setObjectName("widget_4")
        self.widget_3 = QtWidgets.QWidget(self.widget_4)
        self.widget_3.setGeometry(QtCore.QRect(0, 490, 1001, 141))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.loadImage = QtWidgets.QPushButton(self.widget_3)
        self.loadImage.setObjectName("loadImage")
        self.loadImage.clicked.connect(self.onButtonClick)
        self.horizontalLayout_2.addWidget(self.loadImage)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.widget_3)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.onpushButtonClick)
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.widget_2 = QtWidgets.QWidget(self.widget_4)
        self.widget_2.setGeometry(QtCore.QRect(9, 9, 991, 521))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.iamge = QtWidgets.QLabel(self.widget_2)
        self.iamge.setText("")
        self.iamge.setObjectName("iamge")
        self.horizontalLayout.addWidget(self.iamge)
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.result1 = QtWidgets.QLabel(self.widget)
        self.result1.setText("")
        self.result1.setObjectName("result1")
        self.verticalLayout.addWidget(self.result1)
        self.result2 = QtWidgets.QLabel(self.widget)
        self.result2.setText("")
        self.result2.setObjectName("result2")
        self.verticalLayout.addWidget(self.result2)
        self.horizontalLayout.addWidget(self.widget)
        TxclUIClass.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(TxclUIClass)
        self.statusBar.setObjectName("statusBar")
        TxclUIClass.setStatusBar(self.statusBar)

        self.retranslateUi(TxclUIClass)
        QtCore.QMetaObject.connectSlotsByName(TxclUIClass)

    def retranslateUi(self, TxclUIClass):
        _translate = QtCore.QCoreApplication.translate
        TxclUIClass.setWindowTitle(_translate("TxclUIClass", "TxclUI"))
        self.iamge.setText(_translate("TxclUIClass", "TextLabel"))
        self.loadImage.setText(_translate("TxclUIClass", "加载图片"))
        self.pushButton.setText(_translate("TxclUIClass", "开始检测"))
        self.result1.setText(_translate("TxclUIClass", "TextLabel"))
        self.result2.setText(_translate("TxclUIClass", "TextLabel"))


    def onButtonClick(self):
        options = QFileDialog.Options()
        options |= QFileDialog.ReadOnly  # 设置只读模式
        file_name, _ = QFileDialog.getOpenFileName(None, 'Open File', '', 'All Files (*);;Text Files (*.txt)',
                                                   options=options)
        if file_name:
            print('打开文件:', file_name)
        self.file_name1 = file_name
        print(self.file_name1)
        pixmap = QPixmap(file_name)  # 替换为实际图片路径
        self.iamge.setPixmap(pixmap)



        #predict.ss()
        #self.result1.setPixmap()

    def onpushButtonClick(self):
        print("1")
        print(self.file_name1)
        r = predict.predictTEST(self.file_name1)
        print("2")
        my_string = ''.join(r)
        font = QFont('Arial', 32)
        self.result2.setFont(font)
        self.result2.setText(my_string)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_TxclUIClass()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())